#!/bin/bash

# Launch the passed in URL as a web app in the default browser (or chromium if the default doesn't support --app).

browser=$(xdg-settings get default-web-browser)

# Try Chrome-based browsers for --app support, regardless of default browser
for browser in "vivaldi-stable.desktop" "chromium.desktop" "google-chrome.desktop" "brave-browser.desktop"; do
  if [ -f {~/.local,~/.nix-profile,/usr}/share/applications/$browser ]; then
    break
  fi
done

app_param="--app=$1"

exec setsid uwsm-app -- $(sed -n 's/^Exec=\([^ ]*\).*/\1/p' {~/.local,~/.nix-profile,/usr}/share/applications/$browser 2>/dev/null | head -1) $app_param "${@:2}"
